const copy = {
  en: {
    eyebrow:'PORTFOLIO / 2026', role:'AI undergraduate building reliable agent systems and applied LLM products.', navAbout:'About', navExperience:'Experience', navWork:'Selected work', aboutTitle:'Curious about how intelligent systems become genuinely useful.', aboutP1:'I’m a third-year undergraduate studying Artificial Intelligence at Peking University, focused on foundation models and agent systems. I enjoy turning ambiguous, real-world tasks into dependable technical products.', aboutP2:'My recent work spans multi-agent search, tool use, retrieval-augmented generation, and evaluation. I’m currently seeking software engineering, applied AI, and research internships.', factSchoolLabel:'EDUCATION', factSchool:'Peking University', factMajorLabel:'FOCUS', factMajor:'AI · Foundation Models · Agents', factDateLabel:'EXPECTED', factDate:'Jun 2027', experienceTitle:'Experience', experienceNote:'Building systems that search, reason, and improve.', baiduDate:'DEC 2025 — PRESENT', baiduTitle:'AI Strategy Intern <a href="https://www.baidu.com" target="_blank" rel="noreferrer">@ Baidu ↗</a>', baiduBody:'Developing general-purpose agent capabilities for complex information retrieval and task execution. Built a multi-agent deep-search workflow, improved query understanding and reranking, and helped automate evaluation loops for faster strategy iteration.', pkuDate:'MAR 2025 — AUG 2025', pkuTitle:'Research Intern <span>@ Peking University Law School</span>', pkuBody:'Improved legal-domain RAG generation through a two-stage SFT + reinforcement-learning approach. Built a 1,300+ document legal corpus, developed high-quality training data, and improved results on the jecqa benchmark by 5 percentage points.', workTitle:'Selected work', workNote:'A closer look at systems I have helped build.', project1Kicker:'AGENT SYSTEMS · BAIDU', project1Title:'Multi-agent deep search for complex tasks', project1Body:'Designed a specialized User Agent + Assistant Agent workflow that decomposes questions, chooses tools, and refines search directions across multiple turns. The system supports differentiated paths for many task intents and integrates search, finance, academic, and browser tools.', project1Metric1:'98% intent accuracy', project1Metric2:'94% resource coverage', project2Kicker:'APPLIED RESEARCH · RAG', project2Title:'Legal RAG with SFT + RL training', project2Body:'Investigated how a model can learn to cite legal provisions more reliably. I helped construct a legal knowledge base and an experimental framework to identify the contribution of retrieval, SFT, and reinforcement learning.', project2Metric1:'1,300+ legal documents', project2Metric2:'+5 pp on jecqa', footer:'Designed and built by Yueying Luo. Open to internship opportunities.'
  },
  zh: {
    eyebrow:'个人作品集 / 2026', role:'北京大学人工智能本科生，专注于可靠的智能体系统与大模型应用。', navAbout:'关于我', navExperience:'经历', navWork:'代表工作', aboutTitle:'我关心智能系统如何真正解决现实问题。', aboutP1:'我是北京大学人工智能专业本科三年级学生，关注基础模型与智能体系统。我喜欢把模糊的真实需求转化为可靠、可落地的技术产品。', aboutP2:'近期工作涉及多智能体搜索、工具调用、检索增强生成与评测。我正在寻找软件工程、应用 AI 与研究方向的实习机会。', factSchoolLabel:'教育经历', factSchool:'北京大学', factMajorLabel:'关注方向', factMajor:'人工智能 · 基础模型 · 智能体', factDateLabel:'预计毕业', factDate:'2027 年 6 月', experienceTitle:'实习与研究经历', experienceNote:'构建能够检索、推理并持续优化的系统。', baiduDate:'2025 年 12 月 — 至今', baiduTitle:'通用智能体策略实习生 <a href="https://www.baidu.com" target="_blank" rel="noreferrer">@ 百度 ↗</a>', baiduBody:'面向复杂信息检索与任务执行，研发通用智能体能力。参与多智能体深度搜索工作流、query 理解和重排优化，并搭建自动化评测闭环以加速策略迭代。', pkuDate:'2025 年 3 月 — 2025 年 8 月', pkuTitle:'研究实习生 <span>@ 北京大学法学院</span>', pkuBody:'通过两阶段 SFT + 强化学习提升法律领域 RAG 的生成质量。构建 1,300+ 条法律文档语料库与高质量训练数据，在 jecqa 评测集上取得 5 个百分点的提升。', workTitle:'代表工作', workNote:'深入了解我参与构建的系统。', project1Kicker:'智能体系统 · 百度', project1Title:'面向复杂任务的多智能体深度搜索', project1Body:'设计由 User Agent 与 Assistant Agent 协同的工作流，将复杂问题拆解为搜索子任务，在多轮执行中自主选择工具并优化搜索方向。系统支持不同任务意图的差异化路径，集成通用搜索、财经、学术与浏览器工具。', project1Metric1:'意图识别准确率 98%', project1Metric2:'资源覆盖率 94%', project2Kicker:'应用研究 · RAG', project2Title:'SFT + RL 两阶段法律 RAG 训练', project2Body:'探索如何让模型更可靠地引用法律条文。参与构建法律知识库和实验框架，分析检索、SFT 与强化学习对模型表现的贡献。', project2Metric1:'1,300+ 法律文档', project2Metric2:'jecqa +5 pp', footer:'由罗玥萦设计与开发。期待 AI、软件工程及研究实习机会。'
  }
};
let lang='en';
const toggle=document.querySelector('#language-toggle');
function render(){document.documentElement.lang=lang;document.title=lang==='en'?'Yueying Luo | AI & Agent Systems':'罗玥萦 | 人工智能与智能体系统';document.querySelectorAll('[data-i18n]').forEach(el=>{el.innerHTML=copy[lang][el.dataset.i18n]});toggle.textContent=lang==='en'?'中文':'EN';}
toggle.addEventListener('click',()=>{lang=lang==='en'?'zh':'en';render();});
